import asyncio
import json
from unittest.mock import Mock

import pytest
from pydantic import TypeAdapter, ValidationError

from src.providers.voice_control import RtcAction, RtcScreen, VoiceControl
from src.providers.voice_provider import VoiceTaskUpdate
from src.providers.voice_registry import provider_voice_catalog
from src.providers.volcengine_rtc_session import VolcengineRtcSession
from src.providers.volcengine_rtc_token import rtc_token
from src.providers.volcengine_rtc_voice import VolcengineRtcVoiceProvider
from src.voice_settings import VoiceSettings

SETTINGS = VoiceSettings(provider_id="rtc", model="doubao-seed-2-0-lite-260428", voice="zh_female_vv_uranus_bigtts")


def test_token_matches_official_javascript_sdk_vector():
    # Independently generated by volcengine/rtc-aigc-demo's AccessToken SDK.
    assert rtc_token("123456789012345678901234", "example-key", "room", "user", issued=1700000000, nonce=42) == (
        "001123456789012345678901234OAAqAAAAAPFTZRD/U2UEAHJvb20EAHVzZXIFAAAAEP9TZQEAEP9TZQIAEP9TZQMAEP9TZQQAEP9TZSAAq5vuyA7T9r4Y7y6O07DkSTbJBm0QDZuYcj8220wlpio=")


def test_catalog_is_explicit_and_does_not_mix_native_s2s_speakers():
    config = {"type": "doubao", "baseUrl": "https://rtc.volcengineapi.com", "speechSecretAccessKey": "private-key"}
    catalog = provider_voice_catalog(config)
    assert catalog["id"] == "volcengine-rtc" and catalog["delegation"] is True
    assert "private-key" not in json.dumps(catalog)
    with pytest.raises(ValueError):
        VolcengineRtcVoiceProvider.validate(SETTINGS.model_copy(update={"voice": "saturn_zh_female_aojiaonvyou_tob"}))


@pytest.mark.parametrize("body", [
    {"action": "screen", "enabled": True, "fps": 0},
    {"action": "screen", "enabled": True, "fps": 31},
    {"action": "screen", "enabled": "true", "fps": 5},
    {"action": "activate", "AppId": "attacker-app"},
    {"action": "heartbeat", "RoomId": "other-room"},
])
def test_control_never_accepts_identity_override_or_invalid_rate(body):
    with pytest.raises(ValidationError):
        TypeAdapter(VoiceControl).validate_python(body)


def test_activate_vision_feedback_and_idempotent_teardown():
    async def run():
        api = Mock(); api.post_json.return_value = {"Result": "ok"}
        session = VolcengineRtcSession(api, "app", "room", "user", "bot", "原节点历史", SETTINGS)
        try:
            assert api.post_json.call_count == 0
            await session.control(RtcAction(action="activate"))
            await session.control(RtcAction(action="activate"))
            assert api.post_json.call_count == 1
            start = api.post_json.call_args.args[2]
            assert "原节点历史" in start["Config"]["LLMConfig"]["SystemMessages"][0]
            assert start["Config"]["LLMConfig"]["VisionConfig"]["Enable"] is False
            assert start["Config"]["LLMConfig"]["VisionConfig"]["SnapshotConfig"]["Interval"] == 100
            assert start["AgentConfig"]["TargetUserId"] == ["user"]
            for fps in [1, 30]:
                await session.control(RtcScreen(action="screen", enabled=True, fps=fps))
                vision = api.post_json.call_args.args[2]["Parameters"]["Config"]["LLMConfig"]["VisionConfig"]
                assert vision == {"Enable": True, "SnapshotConfig": {"StreamType": 1}}
            first = VoiceTaskUpdate(status="queued", text="", task_id="node-task")
            assert await session.deliver_update("tool-call", first) == "accepted"
            ack = api.post_json.call_args.args[2]
            assert ack["Command"] == "function"
            assert json.loads(ack["Message"])["ToolCallID"] == "tool-call"
            assert await session.deliver_update("tool-call", first) == "duplicate"
            session.last_progress["tool-call"] = 0
            await session.deliver_update("tool-call", VoiceTaskUpdate(status="running", text="正在查资料", task_id="node-task"))
            await session.deliver_update("tool-call", VoiceTaskUpdate(status="completed", text="查到结果", task_id="node-task"))
            update = api.post_json.call_args.args[2]
            assert update["InterruptMode"] == 2 and update["Command"] == "ExternalTextToLLM"
            assert "查到结果" in update["Message"]
            await session.control(RtcScreen(action="screen", enabled=False, fps=30))
        finally:
            await session.aclose(); await session.aclose()
        assert [call.args[0] for call in api.post_json.call_args_list].count("StopVoiceChat") == 1
        assert session.watchdog.done()
        with pytest.raises(ValueError, match="已结束"):
            await session.control(RtcAction(action="heartbeat"))
    asyncio.run(run())


def test_ambiguous_activation_failure_still_stops_cloud_task():
    async def run():
        api = Mock(); api.post_json.side_effect = [ValueError("transport timed out"), {"Result": "ok"}]
        session = VolcengineRtcSession(api, "app", "room", "user", "bot", "", SETTINGS)
        with pytest.raises(ValueError, match="timed out"):
            await session.control(RtcAction(action="activate"))
        await session.aclose()
        assert api.post_json.call_args.args[0] == "StopVoiceChat"
    asyncio.run(run())
