"""Schema fields for advanced audio_generation operations."""

ADVANCED_AUDIO_DEFAULTS = {
    "simultrans_source_audio": "",
    "simultrans_mode": "s2t",
    "simultrans_source_language": "zh",
    "simultrans_target_language": "en",
    "simultrans_speaker": "",
    "simultrans_target_format": "ogg_opus",
    "simultrans_target_rate": "24000",
    "simultrans_hot_words": "",
    "simultrans_glossary": "",
    "simultrans_boosting_table_id": "",
    "simultrans_boosting_table_name": "",
    "simultrans_correct_table_id": "",
    "simultrans_correct_table_name": "",
    "simultrans_denoise": False,
    "simultrans_enable_speaker_info": False,
    "simultrans_resource_id": "volc.service_type.10053",
    "simultrans_chunk_ms": 80,
    "realtime_input_mode": "audio_file",
    "realtime_source_audio": "",
    "realtime_text": "",
    "realtime_model": "2.2.0.0",
    "realtime_speaker": "",
    "realtime_bot_name": "",
    "realtime_system_role": "",
    "realtime_speaking_style": "",
    "realtime_character_manifest": "",
    "realtime_strict_audit": True,
    "realtime_speech_rate": 0,
    "realtime_loudness_rate": 0,
    "realtime_resource_id": "volc.speech.dialog",
    "realtime_chunk_ms": 20,
    "podcast_action": "0",
    "podcast_input_text": "",
    "podcast_input_url": "",
    "podcast_prompt_text": "",
    "podcast_nlp_texts": "",
    "podcast_speakers": "",
    "podcast_random_speaker_order": True,
    "podcast_format": "mp3",
    "podcast_sample_rate": "24000",
    "podcast_speech_rate": 0,
    "podcast_use_head_music": True,
    "podcast_use_tail_music": False,
    "podcast_return_audio_url": True,
    "podcast_strict_audit": False,
    "podcast_input_text_max_length": "",
    "podcast_resource_id": "volc.service_type.10050",
    "minutes_source_url": "",
    "minutes_file_type": "audio",
    "minutes_source_language": "zh_cn",
    "minutes_all_activate": True,
    "minutes_speaker_identification": True,
    "minutes_number_of_speakers": 0,
    "minutes_hot_words": "",
    "minutes_need_word_time_series": True,
    "minutes_translation_enabled": False,
    "minutes_target_language": "en_us",
    "minutes_information_types": "",
    "minutes_summarization_enabled": True,
    "minutes_chapter_enabled": True,
    "minutes_resource_id": "volc.lark.minutes",
    "minutes_poll_interval_seconds": 30,
    "minutes_poll_timeout_seconds": 7200,
}

_MINUTES = ["minutes"]
_PODCAST = ["podcast"]
_REALTIME = ["realtime"]
_SIMULTRANS = ["simultrans"]

ADVANCED_AUDIO_SCHEMA = {
    "simultrans_source_audio": {
        "type": "string",
        "label": "simultrans_source_audio",
        "description": "Local 16 kHz, 16-bit, mono PCM WAV. An input-bar audio attachment takes precedence.",
        "operations": _SIMULTRANS,
    },
    "simultrans_mode": {
        "type": "select",
        "label": "simultrans_mode",
        "options": [{"value": value, "label": value} for value in ("s2t", "s2s")],
        "operations": _SIMULTRANS,
    },
    "simultrans_source_language": {"type": "combobox", "label": "simultrans_source_language", "operations": _SIMULTRANS},
    "simultrans_target_language": {"type": "combobox", "label": "simultrans_target_language", "operations": _SIMULTRANS},
    "simultrans_speaker": {
        "type": "combobox",
        "label": "simultrans_speaker",
        "options": [
            {"value": "zh_female_vv_uranus_bigtts", "label": "zh_female_vv_uranus_bigtts"},
            {"value": "zh_male_jingqiangkanye_emo_mars_bigtts", "label": "zh_male_jingqiangkanye_emo_mars_bigtts"},
        ],
        "operations": _SIMULTRANS,
    },
    "simultrans_target_format": {
        "type": "select",
        "label": "simultrans_target_format",
        "options": [{"value": value, "label": value} for value in ("ogg_opus", "pcm")],
        "operations": _SIMULTRANS,
    },
    "simultrans_target_rate": {
        "type": "select",
        "label": "simultrans_target_rate",
        "options": [{"value": str(value), "label": str(value)} for value in (16000, 24000)],
        "operations": _SIMULTRANS,
    },
    "simultrans_hot_words": {"type": "json", "label": "simultrans_hot_words", "operations": _SIMULTRANS},
    "simultrans_glossary": {"type": "json", "label": "simultrans_glossary", "operations": _SIMULTRANS},
    "simultrans_boosting_table_id": {"type": "string", "label": "simultrans_boosting_table_id", "operations": _SIMULTRANS},
    "simultrans_boosting_table_name": {"type": "string", "label": "simultrans_boosting_table_name", "operations": _SIMULTRANS},
    "simultrans_correct_table_id": {"type": "string", "label": "simultrans_correct_table_id", "operations": _SIMULTRANS},
    "simultrans_correct_table_name": {"type": "string", "label": "simultrans_correct_table_name", "operations": _SIMULTRANS},
    "simultrans_denoise": {"type": "boolean", "label": "simultrans_denoise", "operations": _SIMULTRANS},
    "simultrans_enable_speaker_info": {"type": "boolean", "label": "simultrans_enable_speaker_info", "operations": _SIMULTRANS},
    "simultrans_resource_id": {"type": "string", "label": "simultrans_resource_id", "operations": _SIMULTRANS},
    "simultrans_chunk_ms": {"type": "number", "label": "simultrans_chunk_ms", "min": 80, "max": 80, "operations": _SIMULTRANS},
    "realtime_input_mode": {
        "type": "select",
        "label": "realtime_input_mode",
        "options": [{"value": value, "label": value} for value in ("audio_file", "text")],
        "operations": _REALTIME,
    },
    "realtime_source_audio": {
        "type": "string",
        "label": "realtime_source_audio",
        "description": "Local 16 kHz, 16-bit, mono PCM WAV. An input-bar audio attachment takes precedence.",
        "operations": _REALTIME,
    },
    "realtime_text": {"type": "text", "label": "realtime_text", "operations": _REALTIME},
    "realtime_model": {
        "type": "combobox",
        "label": "realtime_model",
        "options": [{"value": value, "label": value} for value in ("1.2.1.1", "2.2.0.0")],
        "operations": _REALTIME,
    },
    "realtime_speaker": {"type": "combobox", "label": "realtime_speaker", "options": [], "operations": _REALTIME},
    "realtime_bot_name": {"type": "string", "label": "realtime_bot_name", "operations": _REALTIME},
    "realtime_system_role": {"type": "text", "label": "realtime_system_role", "operations": _REALTIME},
    "realtime_speaking_style": {"type": "text", "label": "realtime_speaking_style", "operations": _REALTIME},
    "realtime_character_manifest": {"type": "text", "label": "realtime_character_manifest", "operations": _REALTIME},
    "realtime_strict_audit": {"type": "boolean", "label": "realtime_strict_audit", "operations": _REALTIME},
    "realtime_speech_rate": {"type": "number", "label": "realtime_speech_rate", "min": -50, "max": 100, "operations": _REALTIME},
    "realtime_loudness_rate": {"type": "number", "label": "realtime_loudness_rate", "min": -50, "max": 100, "operations": _REALTIME},
    "realtime_resource_id": {"type": "string", "label": "realtime_resource_id", "operations": _REALTIME},
    "realtime_chunk_ms": {"type": "number", "label": "realtime_chunk_ms", "min": 20, "max": 20, "operations": _REALTIME},
    "podcast_action": {
        "type": "select",
        "label": "podcast_action",
        "options": [
            {"value": "0", "label": "Summarize text or URL"},
            {"value": "3", "label": "Synthesize provided dialogue"},
            {"value": "4", "label": "Research prompt"},
        ],
        "operations": _PODCAST,
    },
    "podcast_input_text": {"type": "text", "label": "podcast_input_text", "operations": _PODCAST},
    "podcast_input_url": {"type": "string", "label": "podcast_input_url", "operations": _PODCAST},
    "podcast_prompt_text": {"type": "text", "label": "podcast_prompt_text", "operations": _PODCAST},
    "podcast_nlp_texts": {
        "type": "json",
        "label": "podcast_nlp_texts",
        "description": "Action 3 JSON array of {text, speaker} rounds.",
        "operations": _PODCAST,
    },
    "podcast_speakers": {
        "type": "json",
        "label": "podcast_speakers",
        "description": "Optional JSON array containing exactly two speaker ids.",
        "operations": _PODCAST,
    },
    "podcast_random_speaker_order": {"type": "boolean", "label": "podcast_random_speaker_order", "operations": _PODCAST},
    "podcast_format": {
        "type": "select",
        "label": "podcast_format",
        "options": [{"value": value, "label": value} for value in ("mp3", "ogg_opus", "pcm", "aac")],
        "operations": _PODCAST,
    },
    "podcast_sample_rate": {
        "type": "select",
        "label": "podcast_sample_rate",
        "options": [{"value": str(value), "label": str(value)} for value in (16000, 24000, 48000)],
        "operations": _PODCAST,
    },
    "podcast_speech_rate": {"type": "number", "label": "podcast_speech_rate", "min": -50, "max": 100, "operations": _PODCAST},
    "podcast_use_head_music": {"type": "boolean", "label": "podcast_use_head_music", "operations": _PODCAST},
    "podcast_use_tail_music": {"type": "boolean", "label": "podcast_use_tail_music", "operations": _PODCAST},
    "podcast_return_audio_url": {"type": "boolean", "label": "podcast_return_audio_url", "operations": _PODCAST},
    "podcast_strict_audit": {"type": "boolean", "label": "podcast_strict_audit", "operations": _PODCAST},
    "podcast_input_text_max_length": {"type": "number", "label": "podcast_input_text_max_length", "min": 1, "operations": _PODCAST},
    "podcast_resource_id": {"type": "string", "label": "podcast_resource_id", "operations": _PODCAST},
    "minutes_source_url": {
        "type": "string",
        "label": "minutes_source_url",
        "description": "Public HTTP(S) audio/video URL; the legacy minutes endpoint does not accept a local upload.",
        "operations": _MINUTES,
    },
    "minutes_file_type": {
        "type": "select",
        "label": "minutes_file_type",
        "options": [{"value": value, "label": value} for value in ("audio", "video")],
        "operations": _MINUTES,
    },
    "minutes_source_language": {
        "type": "select",
        "label": "minutes_source_language",
        "options": [{"value": value, "label": value} for value in ("zh_cn", "en_us")],
        "operations": _MINUTES,
    },
    "minutes_all_activate": {"type": "boolean", "label": "minutes_all_activate", "operations": _MINUTES},
    "minutes_speaker_identification": {"type": "boolean", "label": "minutes_speaker_identification", "operations": _MINUTES},
    "minutes_number_of_speakers": {"type": "number", "label": "minutes_number_of_speakers", "min": 0, "operations": _MINUTES},
    "minutes_hot_words": {"type": "text", "label": "minutes_hot_words", "operations": _MINUTES},
    "minutes_need_word_time_series": {"type": "boolean", "label": "minutes_need_word_time_series", "operations": _MINUTES},
    "minutes_translation_enabled": {"type": "boolean", "label": "minutes_translation_enabled", "operations": _MINUTES},
    "minutes_target_language": {
        "type": "select",
        "label": "minutes_target_language",
        "options": [{"value": value, "label": value} for value in ("zh_cn", "en_us")],
        "operations": _MINUTES,
    },
    "minutes_information_types": {
        "type": "json",
        "label": "minutes_information_types",
        "description": "JSON string array containing todo_list and/or question_answer.",
        "operations": _MINUTES,
    },
    "minutes_summarization_enabled": {"type": "boolean", "label": "minutes_summarization_enabled", "operations": _MINUTES},
    "minutes_chapter_enabled": {"type": "boolean", "label": "minutes_chapter_enabled", "operations": _MINUTES},
    "minutes_resource_id": {"type": "string", "label": "minutes_resource_id", "operations": _MINUTES},
    "minutes_poll_interval_seconds": {"type": "number", "label": "minutes_poll_interval_seconds", "min": 0.2, "operations": _MINUTES},
    "minutes_poll_timeout_seconds": {"type": "number", "label": "minutes_poll_timeout_seconds", "min": 1, "operations": _MINUTES},
}
