"""Schema contract for the Agent node's audio_generation SupportMode."""

from nodes.agent_audio_advanced_schema import ADVANCED_AUDIO_DEFAULTS, ADVANCED_AUDIO_SCHEMA

AUDIO_CONFIG_DEFAULTS = {
    "audio_operation": "generate",
    "audio_model": "seed-audio-1.0",
    "audio_speaker": "",
    "tts_model": "seed-tts-2.0-standard",
    "tts_speaker": "",
    "tts_resource_id": "seed-tts-2.0",
    "audio_references": [],
    "audio_format": "mp3",
    "audio_sample_rate": "48000",
    "tts_format": "mp3",
    "tts_sample_rate": "24000",
    "tts_bit_rate": 128000,
    "tts_speech_rate": 0,
    "tts_loudness_rate": 0,
    "tts_pitch": 0,
    "tts_enable_subtitle": False,
    "tts_aigc_watermark": False,
    "tts_metadata_watermark": "",
    "audio_speech_rate": 0,
    "audio_loudness_rate": 0,
    "audio_pitch_rate": 0,
    "audio_enable_subtitle": False,
    "audio_aigc_watermark": False,
    "audio_metadata_watermark": "",
    "audio_filename_prefix": "generated_audio",
    "tts_ssml": "",
    "tts_additions": "",
    "tts_context_texts": "",
    "tts_section_id": "",
    "tts_tone_fidelity": False,
    "tts_async_resource_id": "seed-tts-2.0",
    "tts_async_poll_interval_seconds": 5,
    "tts_async_poll_timeout_seconds": 3600,
    "asr_source_audio": "",
    "asr_resource_id": "volc.bigasr.auc_turbo",
    "asr_uid": "",
    "asr_model_name": "bigmodel",
    "asr_enable_itn": True,
    "asr_enable_punc": True,
    "asr_enable_ddc": True,
    "asr_enable_speaker_info": False,
    "asr_standard_resource_id": "volc.seedasr.auc",
    "asr_idle_resource_id": "volc.bigasr.auc_idle",
    "asr_language": "",
    "asr_audio_format": "",
    "asr_audio_codec": "raw",
    "asr_audio_rate": 16000,
    "asr_audio_bits": 16,
    "asr_audio_channel": 1,
    "asr_show_utterances": True,
    "asr_enable_channel_split": False,
    "asr_poll_interval_seconds": 5,
    "asr_poll_timeout_seconds": 3600,
    "asr_stream_resource_id": "volc.seedasr.sauc.duration",
    "asr_stream_endpoint_mode": "bidirectional",
    "asr_stream_chunk_ms": 200,
    "translation_source_language": "",
    "translation_target_language": "en",
    "translation_text_list": "",
    "translation_corpus": "",
    "translation_resource_id": "volc.speech.mt",
    **ADVANCED_AUDIO_DEFAULTS,
}

AUDIO_CONFIG_SCHEMA = {
    "audio_operation": {
        "type": "select",
        "label": "audio_operation",
        "options": [
            {"value": "generate", "label": "Audio Generation HTTP"},
            {"value": "tts_http", "label": "TTS HTTP Chunked"},
            {"value": "tts_async", "label": "TTS Async Long Text"},
            {"value": "tts_ws_unidirectional", "label": "TTS WebSocket Unidirectional"},
            {"value": "tts_ws_bidirectional", "label": "TTS WebSocket Bidirectional"},
            {"value": "asr_flash", "label": "ASR File Flash"},
            {"value": "asr_standard", "label": "ASR File Standard"},
            {"value": "asr_idle", "label": "ASR File Idle"},
            {"value": "asr_stream", "label": "ASR Streaming WebSocket"},
            {"value": "realtime", "label": "Realtime Dialogue"},
            {"value": "simultrans", "label": "Simultaneous Interpretation"},
            {"value": "translate", "label": "Machine Translation"},
            {"value": "podcast", "label": "Podcast Generation"},
            {"value": "minutes", "label": "Audio Minutes"},
        ],
        "description": "Protocol operation inside the audio_generation SupportMode.",
    },
    "audio_model": {
        "type": "combobox",
        "label": "audio_model",
        "options": [
            {"value": "seed-audio-1.0", "label": "seed-audio-1.0"},
            {"value": "seed-audio-1.0-multilingual", "label": "seed-audio-1.0-multilingual"},
        ],
        "description": "Model id. Choose a documented value or enter a provider-supported id.",
        "operations": ["generate"],
    },
    "audio_speaker": {
        "type": "combobox",
        "label": "audio_speaker",
        "options": [],
        "description": "Optional speaker id. Mutually exclusive with audio/image reference resources.",
        "operations": ["generate"],
    },
    "tts_model": {
        "type": "combobox",
        "label": "tts_model",
        "options": [{"value": "seed-tts-2.0-standard", "label": "seed-tts-2.0-standard"}],
        "operations": ["tts_http", "tts_async", "tts_ws_unidirectional", "tts_ws_bidirectional"],
    },
    "tts_speaker": {
        "type": "combobox",
        "label": "tts_speaker",
        "options": [],
        "operations": ["tts_http", "tts_async", "tts_ws_unidirectional", "tts_ws_bidirectional"],
    },
    "tts_resource_id": {
        "type": "combobox",
        "label": "tts_resource_id",
        "options": [
            {"value": "seed-tts-2.0", "label": "seed-tts-2.0"},
            {"value": "seed-icl-2.0", "label": "seed-icl-2.0"},
        ],
        "operations": ["tts_http", "tts_ws_unidirectional", "tts_ws_bidirectional"],
    },
    "audio_references": {
        "type": "file_list",
        "label": "audio_references",
        "description": "Optional project files selected from the file tree. Audio and image references cannot be mixed.",
        "operations": ["generate"],
    },
    "audio_format": {
        "type": "select",
        "label": "audio_format",
        "options": [{"value": value, "label": value} for value in ("wav", "mp3", "pcm", "ogg_opus")],
        "operations": ["generate"],
    },
    "audio_sample_rate": {
        "type": "select",
        "label": "audio_sample_rate",
        "options": [{"value": str(value), "label": str(value)} for value in (8000, 16000, 24000, 32000, 44100, 48000)],
        "operations": ["generate"],
    },
    "tts_format": {
        "type": "select",
        "label": "tts_format",
        "options": [{"value": value, "label": value} for value in ("mp3", "pcm", "ogg_opus", "wav")],
        "operations": ["tts_http", "tts_async", "tts_ws_unidirectional", "tts_ws_bidirectional"],
    },
    "tts_sample_rate": {
        "type": "select",
        "label": "tts_sample_rate",
        "options": [{"value": str(value), "label": str(value)} for value in (8000, 16000, 22050, 24000, 32000, 44100, 48000)],
        "operations": ["tts_http", "tts_async", "tts_ws_unidirectional", "tts_ws_bidirectional"],
    },
    "tts_bit_rate": {
        "type": "number",
        "label": "tts_bit_rate",
        "min": 64000,
        "max": 160000,
        "operations": ["tts_http", "tts_async", "tts_ws_unidirectional", "tts_ws_bidirectional"],
    },
    "audio_speech_rate": {"type": "number", "label": "audio_speech_rate", "min": -50, "max": 100, "operations": ["generate"]},
    "audio_loudness_rate": {"type": "number", "label": "audio_loudness_rate", "min": -50, "max": 100, "operations": ["generate"]},
    "audio_pitch_rate": {"type": "number", "label": "audio_pitch_rate", "min": -12, "max": 12, "operations": ["generate"]},
    "audio_enable_subtitle": {"type": "boolean", "label": "audio_enable_subtitle", "operations": ["generate"]},
    "tts_speech_rate": {"type": "number", "label": "tts_speech_rate", "min": -50, "max": 100, "operations": ["tts_http", "tts_async", "tts_ws_unidirectional", "tts_ws_bidirectional"]},
    "tts_loudness_rate": {"type": "number", "label": "tts_loudness_rate", "min": -50, "max": 100, "operations": ["tts_http", "tts_async", "tts_ws_unidirectional", "tts_ws_bidirectional"]},
    "tts_pitch": {"type": "number", "label": "tts_pitch", "min": -12, "max": 12, "operations": ["tts_http", "tts_ws_unidirectional", "tts_ws_bidirectional"]},
    "tts_enable_subtitle": {"type": "boolean", "label": "tts_enable_subtitle", "operations": ["tts_http", "tts_async", "tts_ws_unidirectional", "tts_ws_bidirectional"]},
    "tts_aigc_watermark": {"type": "boolean", "label": "tts_aigc_watermark", "operations": ["tts_http", "tts_ws_unidirectional", "tts_ws_bidirectional"]},
    "tts_metadata_watermark": {"type": "json", "label": "tts_metadata_watermark", "operations": ["tts_http", "tts_ws_unidirectional", "tts_ws_bidirectional"]},
    "audio_aigc_watermark": {"type": "boolean", "label": "audio_aigc_watermark", "operations": ["generate"]},
    "audio_metadata_watermark": {
        "type": "json",
        "label": "audio_metadata_watermark",
        "description": "Optional aigc_metadata object for an implicit audio watermark.",
        "operations": ["generate"],
    },
    "tts_ssml": {"type": "text", "label": "tts_ssml", "operations": ["tts_http", "tts_ws_unidirectional"]},
    "tts_additions": {
        "type": "json",
        "label": "tts_additions",
        "description": "Optional additions object; it is serialized to the API's additions JSON string.",
        "operations": ["tts_http", "tts_async", "tts_ws_unidirectional", "tts_ws_bidirectional"],
    },
    "tts_context_texts": {
        "type": "json",
        "label": "tts_context_texts",
        "description": "Optional JSON string array of voice instructions.",
        "operations": ["tts_http", "tts_ws_unidirectional", "tts_ws_bidirectional"],
    },
    "tts_section_id": {"type": "string", "label": "tts_section_id", "operations": ["tts_http", "tts_ws_unidirectional", "tts_ws_bidirectional"]},
    "tts_tone_fidelity": {"type": "boolean", "label": "tts_tone_fidelity", "operations": ["tts_http", "tts_ws_unidirectional"]},
    "tts_async_resource_id": {"type": "combobox", "label": "tts_async_resource_id", "operations": ["tts_async"]},
    "tts_async_poll_interval_seconds": {"type": "number", "label": "tts_async_poll_interval_seconds", "min": 0.2, "operations": ["tts_async"]},
    "tts_async_poll_timeout_seconds": {"type": "number", "label": "tts_async_poll_timeout_seconds", "min": 1, "operations": ["tts_async"]},
    "asr_source_audio": {
        "type": "string",
        "label": "asr_source_audio",
        "description": "Audio path or public URL. An input-bar audio attachment takes precedence.",
        "operations": ["asr_flash", "asr_standard", "asr_idle", "asr_stream"],
    },
    "asr_resource_id": {
        "type": "combobox",
        "label": "asr_resource_id",
        "options": [{"value": "volc.bigasr.auc_turbo", "label": "volc.bigasr.auc_turbo"}],
        "operations": ["asr_flash"],
    },
    "asr_uid": {
        "type": "string",
        "label": "asr_uid",
        "description": "Optional request user uid. Defaults to the configured speech App ID, then API Key as in the official example.",
        "operations": ["asr_flash", "asr_standard", "asr_idle", "asr_stream"],
    },
    "asr_model_name": {"type": "string", "label": "asr_model_name", "operations": ["asr_flash", "asr_standard", "asr_idle", "asr_stream"]},
    "asr_enable_itn": {"type": "boolean", "label": "asr_enable_itn", "operations": ["asr_flash", "asr_standard", "asr_idle", "asr_stream"]},
    "asr_enable_punc": {"type": "boolean", "label": "asr_enable_punc", "operations": ["asr_flash", "asr_standard", "asr_idle", "asr_stream"]},
    "asr_enable_ddc": {"type": "boolean", "label": "asr_enable_ddc", "operations": ["asr_flash", "asr_standard", "asr_idle", "asr_stream"]},
    "asr_enable_speaker_info": {"type": "boolean", "label": "asr_enable_speaker_info", "operations": ["asr_flash", "asr_standard", "asr_idle", "asr_stream"]},
    "asr_standard_resource_id": {
        "type": "combobox",
        "label": "asr_standard_resource_id",
        "options": [
            {"value": "volc.seedasr.auc", "label": "volc.seedasr.auc (2.0)"},
            {"value": "volc.bigasr.auc", "label": "volc.bigasr.auc (1.0)"},
        ],
        "operations": ["asr_standard"],
    },
    "asr_idle_resource_id": {"type": "string", "label": "asr_idle_resource_id", "operations": ["asr_idle"]},
    "asr_language": {"type": "string", "label": "asr_language", "operations": ["asr_standard", "asr_idle"]},
    "asr_audio_format": {"type": "string", "label": "asr_audio_format", "operations": ["asr_standard", "asr_idle"]},
    "asr_audio_codec": {"type": "string", "label": "asr_audio_codec", "operations": ["asr_standard", "asr_idle"]},
    "asr_audio_rate": {"type": "number", "label": "asr_audio_rate", "min": 8000, "operations": ["asr_standard", "asr_idle"]},
    "asr_audio_bits": {"type": "number", "label": "asr_audio_bits", "min": 16, "max": 16, "operations": ["asr_standard", "asr_idle"]},
    "asr_audio_channel": {"type": "number", "label": "asr_audio_channel", "min": 1, "max": 2, "operations": ["asr_standard", "asr_idle"]},
    "asr_show_utterances": {"type": "boolean", "label": "asr_show_utterances", "operations": ["asr_standard", "asr_idle"]},
    "asr_enable_channel_split": {"type": "boolean", "label": "asr_enable_channel_split", "operations": ["asr_standard", "asr_idle"]},
    "asr_poll_interval_seconds": {"type": "number", "label": "asr_poll_interval_seconds", "min": 0.2, "operations": ["asr_standard", "asr_idle"]},
    "asr_poll_timeout_seconds": {"type": "number", "label": "asr_poll_timeout_seconds", "min": 1, "operations": ["asr_standard", "asr_idle"]},
    "asr_stream_resource_id": {"type": "combobox", "label": "asr_stream_resource_id", "operations": ["asr_stream"]},
    "asr_stream_endpoint_mode": {
        "type": "select",
        "label": "asr_stream_endpoint_mode",
        "options": [
            {"value": "bidirectional", "label": "bidirectional"},
            {"value": "optimized", "label": "optimized"},
            {"value": "stream_input", "label": "stream_input"},
        ],
        "operations": ["asr_stream"],
    },
    "asr_stream_chunk_ms": {"type": "number", "label": "asr_stream_chunk_ms", "min": 100, "max": 200, "operations": ["asr_stream"]},
    "translation_source_language": {"type": "string", "label": "translation_source_language", "operations": ["translate"]},
    "translation_target_language": {"type": "string", "label": "translation_target_language", "operations": ["translate"]},
    "translation_text_list": {
        "type": "json",
        "label": "translation_text_list",
        "description": "Optional JSON string array. When empty, the current input text is translated as one item.",
        "operations": ["translate"],
    },
    "translation_corpus": {"type": "json", "label": "translation_corpus", "operations": ["translate"]},
    "translation_resource_id": {"type": "string", "label": "translation_resource_id", "operations": ["translate"]},
    "audio_filename_prefix": {"type": "string", "label": "audio_filename_prefix", "operations": ["generate", "tts_http", "tts_async", "tts_ws_unidirectional", "tts_ws_bidirectional"]},
    **ADVANCED_AUDIO_SCHEMA,
}
